language: scala

scala:
  - 2.13.3

# This hopefully gives us IPv6
os: linux
arch: arm64
dist: bionic

jdk:
  - openjdk11
  - openjdk14

env:
  - COURSIER_TTL="1h"

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_script: source openrc-designate.sh

script: sbt -Dsbt.color=true test

after_success: sbt -Dsbt.color=true coverageReport codacyCoverage